import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

// A perfectly transparent 1x1 pixel GIF (43 bytes)
// This is the industry standard for tracking pixels.
const TRANSPARENT_GIF_BUFFER = Buffer.from(
    'R0lGODlhAQABAJAAAP8AAAAAACH5BAUQAAAALAAAAAABAAEAAAICBAEAOw==',
    'base64'
);

export async function GET(request: NextRequest) {
    // 1. Extract the Query Parameters generated by our Chrome Extension
    const searchParams = request.nextUrl.searchParams;
    const emailId = searchParams.get('email_id');

    // If there's no email_id, we still return the GIF so we don't break the sender's email visually
    if (!emailId) {
        return new NextResponse(TRANSPARENT_GIF_BUFFER, {
            status: 200,
            headers: {
                'Content-Type': 'image/gif',
                'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
                'Pragma': 'no-cache',
                'Expires': '0',
            },
        });
    }

    // 2. Extract Request Headers for Analytics
    // Vercel/Next.js routes the request through a proxy, so we check x-forwarded-for first
    const ipAddress = request.headers.get('x-forwarded-for') || (request as any).ip || 'Unknown';
    const userAgent = request.headers.get('user-agent') || 'Unknown';

    try {
        // 3. Write Event to the Database
        // Note: Since this route runs unauthenticated, RLS must allow inserts to tracking_logs
        const { error } = await supabase.from('tracking_logs').insert({
            email_id: emailId,
            event_type: 'open',
            ip_address: ipAddress,
            user_agent: userAgent,
        });

        if (error) {
            console.error('Error inserting tracking log:', error);
            // We log the error internally, but WE DO NOT FAIL THE HTTP REQUEST.
            // If we return a 500 server error, the email client might display a broken image icon.
        }
    } catch (err) {
        console.error('Unexpected error during tracking:', err);
    }

    // 4. Return the 1x1 Transparent GIF
    // We use strict Cache-Control headers to ensure the browser/email client
    // NEVER caches this image. If they cache it, subsequent opens won't trigger a new HTTP GET request.
    return new NextResponse(TRANSPARENT_GIF_BUFFER, {
        status: 200,
        headers: {
            'Content-Type': 'image/gif',
            'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
            'Pragma': 'no-cache',
            'Expires': '0',
        },
    });
}
